### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bmcgonag** [pboehm/ddns#29]
Hello, I keep getting this error when I run the build step.  I think it's coming from the PowerDNS part.  I'm not sure how to resolve it.  If there is more detail that would help you please let me know. 

Host: Ubuntu 20.04 VPS on Digital Ocean

**Comment by pboehm** [comment]
Hello @bmcgonag, this sounds exactly like the problem described and solved here https://github.com/pboehm/ddns/issues/28#issuecomment-726765393 It is not a `ddns` problem but a `docker-compose` problem because one of the ports is probably already used by another application.

**Comment by bmcgonag** [comment]
Let me check it out, but this is a clean VPS I setup just for this purpose, so there shouldn't be anything using the port...but maybe port 53?

**Comment by bmcgonag** [comment]
That was it, ubuntu ties up port 53 so had to free it up. Now just having issues getting to frontend ui.
