### ISSUE TITLE
Securing host registration

### ISSUE THREAD

**Issue by vialcollet** [pboehm/ddns#34]
Hi
Congrats for this great job. I love it.
I was wondering if there is a possiblity to secure new host registration with a password.
The idea is to make it private and prevent random visitors to register their hosts.
Thanks!

**Comment by sliterok** [comment]
Add basicauth to your Caddyfile, e.g: 
```
{$DDNS_CADDY_DOMAIN} {
  tls {$DDNS_CADDY_TLS_EMAIL}
  basicauth / admin password
  proxy / {$DDNS_FRONTEND_HOST} {
    transparent
  }
}
```
Remember that you would also need to add `-u admin:password` to your curl command

**Comment by vialcollet** [comment]
Oh fantastic!
Thanks for your reply
