### ISSUE TITLE
Hosted DDNS Service down or broken?

### ISSUE THREAD

**Issue by moritzhoewer** [pboehm/ddns#42]
Hi,
I noticed earlier today that I could no longer resolve my Dyn DNS hosted on `d.pboehm.de`

DNS is giving server failures
```
{
  "Status": 2,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "casafreitag.d.pboehm.de.",
      "type": 1
    }
  ],
  "Comment": "Name servers refused query (lame delegation?) [104.45.7.23]."
}
```
(https://dns.google/resolve?name=casafreitag.d.pboehm.de&type=A)

And https://ddns.pboehm.de is giving `502 Bad Gateway`.

Is the service down/terminated on purpose or will it be coming back online?

Best regards from Hamburg, Germany

**Comment by pboehm** [comment]
Moin @moritzhoewer 

Thanks for reporting this, the `ddns` docker container was misbehaving mysteriously! I've fixed the setup and everything should work now as expected.

Greetings from Schwerin, Germany 😄

**Comment by moritzhoewer** [comment]
Thanks for fixing it :)

**Comment by MestreLion** [comment]
> and when I try to re-register it (or any other hostname) on https://ddns.pboehm.de, I get a Bad Request error in the Javascript console or a
> 
> ```
> {"error":"Could not register host."}
> ```
> 
> when I manually execute the request.

Having the same issue here. Time to re-open this bug?

**Comment by pboehm** [comment]
@MestreLion please have a look at this recently added section in the README https://github.com/pboehm/ddns#%EF%B8%8F%EF%B8%8F%EF%B8%8F-note-regarding-hosted-version-at-ddnspboehmde

**Comment by inexcode** [comment]
Three years later, and it just now came into my attention that a note in the README linked to my instance (at least, right now it is the only result).

Which was abandoned by me three years ago, when I moved to a house with a static IP. I've been just too lazy to stop a running Docker container. I had no idea it is used by someone.

Well, uh, I don't even know what to say. It just works, and consumes almost no resources.
