### ISSUE TITLE
Installation instructions.

### ISSUE THREAD

**Issue by BonusHunt** [pboehm/ddns#6]
Please update the installation instructions to match the new docker branch, as a newbie its very very hard and frustrating to guess what needs to be done and I feel like such an experienced developer should know better.. Without sounding ungrateful, its absolutely pointless publishing your work on github if only you hold the 'keys' to get it up and running... 

I have docker installed, I am at this stage;

https://i.gyazo.com/aaec40cf831f67c3330b983babd2af34.png

But I have absolutely no clue whats next....? If you are going to take your time to re-write the installation instructions it would be greatly appreciated, due note please do not do a half assed job... Explain what needs to be installed PRIOR to building the docker contents, explain what our domains need to be pointed to in the DNS records from our domain provider.

Thanks.

> It is a thousand times better to have common sense without education than to have education without common sense.

**Comment by BonusHunt** [comment]
Also, please read this - https://stevebennett.me/2012/02/24/10-things-i-hate-about-git/

Specifically;

> 3. Crappy documentation

The man pages are one almighty “fuck you”. They describe the commands from the perspective of a computer scientist, not a user. Case in point:

git-push – Update remote refs along with associated objects

Here’s a description for humans: git-push – Upload changes from your local repository into a remote repository

Update, another example: (thanks cgd)

git-rebase – Forward-port local commits to the updated upstream head

Translation: git-rebase – Sequentially regenerate a series of commits so they can be applied directly to the head node

There is one thing I have always thought strongly about and that is.. You can be as qualified as you wish but if you lack common sense you will always fail

**Comment by pboehm** [comment]
Hello,

I'm sorry that your experience with my little side project is not that positive. 

The docker branch you're referring to, corresponds to a Pull Request https://github.com/pboehm/ddns/pull/2 which is Work in Progress for a long time and is not finished yet and I can't promise that it will be finished in the near future. Unfortunately the current setup, running on ddns.pboehm.org works good enough for me (except the issue with Lets Encrypt, which is fixed in this branch). Providing detailed setup instructions for running the docker setup is definitely one of the key tasks that has to be done.

Greetings

Philipp

**Comment by BonusHunt** [comment]
So, can you not provide setup instructions for the mater branch? They are incomplete/do not work as intended... You skip off vital points like the fact we need to run ./ddns with arguments, or maybe the fact we need to point certain records... Again, running on YOUR END is good enough for you? Why even bother to release the source files if you dont intend for anybody else to use it? That's like inviting me over to your house, giving me the key but not telling me where you live?????

As I said, either look at your installation documents on the master branch and politely edit them or just remove the project is its useless.

**Comment by pboehm** [comment]
The setup instructions definitely require some higher knowledge about the DNS and some other tools (including go and PowerDNS) but this knowledge is required if you want to host it yourself. For users without this knowledge, there is ddns.pboehm.org which can be used by everyone, without having this knowledge. Also the master branch has received no changes for 3 years!

https://github.com/pboehm/ddns/issues/4 contains a comment about the required DNS records, which could be part of future documentation, but currently I have no time for that. And contacting me through various channels like Github, Twitter, Email probably won't change that.

And without being rude, you're not forced to use this project because there are probably other tools and projects available and there is the chance that they have a better documentation.

**Comment by BonusHunt** [comment]
The setup instructions do not require any higher knowledge what are you talking about? The setup instructions are incomplete as ever since this was even published onto github you miss off key steps that are needed, as I explained executing the ./ddns file to enable the backend processing and I am fairly certain their are a few other little things that is causing this to not work, I have the front end setup, its just not delegating an IP to the subdomain. Blatant typos in your documentation also lead to confusion, like how you have used 3 domains as stated above, which would take a whole 20 seconds to fix yet you are adamant you 'do not have time' its just sub-par/poor etiquette.

By publishing this code here, you're surely wanting other people to use it no? If that is not the case why even post it as a public repo, what is the point?

I also would not put any faith into housing my DDNS with you, if you cannot take 5 minutes to go back and fix something that I am sure has taken you a while to do why would I hold any faith? Not to mention, your DDNS service is being abused to host malware, what's funny is your domain is controlled by ICANN, a quick email over to them and your domain will go down faster than you would think.

Regardless, you might think I am being rude or ungrateful and yes I wont lie to a degree I am. You have a great piece of source here that is very useful to me, I have shopped around checking out nsupdate and hopper but they are not what I need, this is exactly what I need. Configuring go, PowerDNS, nginx and supervisor is not the issue here. The issue is and I will say it again, multiple typos which lead to question and incomplete usage instructions.

It honestly baffles my mind why you would not include steps such as needing to run ./ddns in the original documentation, surely common sense comes into play here? I can see you have this superior attitude so it is what it is, but what you are doing goes against the whole point of even releasing your source code here. Ah, the internet in 2017 never ceases to amaze me.

**Comment by pboehm** [comment]
Those three Domain-Records all have their purpose and are no typos. 

`sub.example.com` is the subdomain under which hosts are registered. `dns.example.com` is an `A`-Record pointing to the VM, where the PowerDNS and DDNS is running on. The `NS` record for `sub.example.com` points to this `A` record. `ddns.example.com` is the Record where the Web-Frontend is accessible through. So there is not typo in the README.

There are two places where `ddns` commands are described in the README https://github.com/pboehm/ddns#frontend in the supervisor config and https://github.com/pboehm/ddns#backend in the `pipe.conf` and everytime the correct command is shown using the records described above.

This will be my last comment on this issue and please refrain from posting any other raging comments and feel free to use any other project.

**Comment by BonusHunt** [comment]
Im just trying to make sense of your work dude, If you are unwilling to develop this project and take suggestions/questions I suggest you either;

- Remove the repo from public view.
- Block me (if possible) from leaving comments or go ahead and report me for whatever it is you think I have done.

Nobody is forcing you to reply however as you keep going into this self defence mode, I am not criticising your skillset Phillip I am simply making note that you lack common sense, you can take that as an insult or you can work with me to improve that, either I am happy to do. As you seem to be so adamant I am being toxic/leaving raging comments I will go ahead and demonstrate what a raging comment would be if I was to post a raging comment;

> What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.

Then again, I could also just report your domain to `epag.de` and why not send the same email to your server provider `goneo.de`, while I am there I might as well send an email over to `europol` containing your name, address, contact email, telephone number, multiple forum profiles I found by simply searching your other alias's and of course your photo. Why would that be a thing? Well as you saw if you head over to hopper.pw and see why they closed, your site is featured in multiple tutorials on a well known forum that houses script kiddies and people who like to play with remote administration tools who attempt to install malware on peoples machines without their knowledge. Your site is being used as a DNS relay which is backed up by multiple reports from malware analysis services.

One may presume, that this github page is just a front for you to sell this service potentially? Who knows.. I am not trained to investigate such things so why not allow the appropriate agencies to do so.

**Comment by Intel1146** [comment]
Stop being an asshole, BonusHunt.

**Comment by Intel1146** [comment]
You're threatening him now. If you're referring to HackForums or Nulled.to, then fuck right off. Pboehm has no responsibility whatsoever for what users use the service for. As he stated to me, it is a side project. A kitchen knife manufacturer isn't responsible for people using the knife to kill people, now is he?

Stop trying to be threatening, you really really aren't good at it.
