### ISSUE TITLE
Error with PowerDNS ports in docker-compose.override.yml

### ISSUE THREAD

**Issue by bobthemac** [pboehm/ddns#9]
I am having an error come up when I try to run docker-compose I copied my config file from the sample as stated in your guide and changed all the locations of the files and domains, am I missing something here.

```
ERROR: The Compose file './docker-compose.override.yml' is invalid because:
services.powerdns.ports is invalid: Invalid port "53/udp:53/udp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

**Comment by pboehm** [comment]
Hello thanks for using my little side-project.

It will probably work if you change it to `53:53/udp` (https://docs.docker.com/compose/compose-file/compose-file-v2/#ports). This could be a change, introduced in some version of docker-compose, but I will definitely update the sample file.

Thanks for reporting this

Philipp

**Comment by bobthemac** [comment]
Ok thanks for that it's now working and thanks for making the project public.

**Comment by pboehm** [comment]
I've updated the sample docker-compose.override.yml in ba7d494
